### ISSUE TITLE
Log in with existing credentials

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-52/giffygram-commando-squad#13]
As a gifophile, I want to log in with my credentials

**Given** that a person wants to use Giffygram
**And** has entered in a valid email and password
**When** the person clicks on the login button
**Then** the person should see the list of posts

**Comment by luciidlou** [comment]
Still need to figure out why the page isn't rerendering once the login button is clicked. We can log in with exisiting user credentials, but after we hit the login button, we have to refresh the page to get out of the login page and into the main page

**Comment by luciidlou** [comment]
Fixed the problem I commented above! I just had to use `addEventListener` on `applicationElement` instead of `document` within the `main.js` module
